### PR TITLE
Fix stream cancelling for FetchPolicy.CacheAndNetwork, too

### LINKED ISSUE #51: Link does not get notified when stream isn't listened anymore
Hi,

I think it would be nice if a custom Link would get notified when the Stream it is returning in it's `request` method isn't being listened to anymore.
This would allow for the Link to cancel a Subscription automatically once no one is listening anymore, or to clean up other resources.

Currently, this is not the case. 

This can be shown in this test case, which will time out:

```dart
import 'dart:async';

import 'package:ferry/ferry.dart';
import 'package:gql_exec/gql_exec.dart';
import 'package:gql_exec/src/response.dart';
import 'package:test/test.dart';

import './graphql/all_pokemon.req.gql.dart';


class _StreamCancelTestLink extends Link {
  final Completer hasCanceledStreamCompleter = Completer();

  @override
  Stream<Response> request(Request request, [forward]) async* {
    StreamController<Response> controller =
        StreamController(onCancel: () => print("oncancel controller"));
    StreamSubscription sub;
    try {
      //simulate events coming in, e.g. from a websocket
      sub =
          Stream.periodic(Duration(microseconds: 1), (_) => Response(data: {}))
              .listen(controller.add);
      //yield* should finish when the client stops listening
      yield* controller.stream;
    } finally {
      //this gets called when the client stops listening to the stream
      sub?.cancel();
      controller.close();

      hasCanceledStreamCompleter.complete();
    }
  }
}

void main() {
  test("Can cleanup", () async {
    final link = _StreamCancelTestLink();

    final client = Client(link: link);
    final req1 = AllPokemon(
        fetchPolicy: FetchPolicy.NetworkOnly, buildVars: (b) => b..first = 3);
    expect(link.hasCanceledStreamCompleter.isCompleted, isFalse);
    StreamSubscription subscription;
    subscription = client.responseStream(req1).skip(1).listen((event) async {
      //cancel subscription after first item
      //this ensures the the link.request() method is entered
      await subscription.cancel();
    });
    // the link should complete its "yield*" statement when the subscription is cancelled
    // and complete its completer
    await link.hasCanceledStreamCompleter.future;

    expect(link.hasCanceledStreamCompleter.isCompleted, isTrue);
  });

}
```

I think with two small changes to the Ferry client we can get this behavior. I will open PRs with these changes shortly.

### PR DESCRIPTION
**Pull request by knaeckeKami**
This fixes #51 .

This includes the changes in #52, and fixes for `FetchPolicy.cacheAndNetwork` policy, and extends the test for canceling the streams when they are not listened to anymore for all FetchPolicies.

I am not really sure why these fixes to `FetchPolicy.cacheAndNetwork` are necessary, I know too little about rxdart for this. But with wrapping the network stream in a new StreamController and manually canceling it, the canceling of the stream is passed on the Link, too.

There might be a better with rxdart, which is why I put this fix in a separate PR.

### CODE REVIEW

**Comment by smkhalsa** [comment]
Thanks for the PR!

I remember there was a reason we used async await for the network request, but I'm travelling now and can't dog into it. 

I'll try to take another look next week.

File: ferry/lib/src/client.dart [hunk 1]
```diff
@@ -160,24 +170,22 @@ class Client {
...
-        yield QueryResponse(
-          queryRequest: queryRequest,
-          data: (response.data == null || response.data.isEmpty)
-              ? null
-              : queryRequest.parseData(response.data),
-          graphqlErrors: response.errors,
-          dataSource: DataSource.Link,
-        );
-      }
+      return link.request(queryRequest).map((response) => QueryResponse(
```
Comment (smkhalsa) [inline ferry/lib/src/client.dart:175]: I believe the reason I originally used async await here is so that data events will continue to be received after an error. For example, we might have a GraphQL Subscription that gives us the following events:

Data  --  Data -- Error -- Data

If we simply map the stream, I believe it will stop listening for data events after the error, but I haven't tested this.

We might be able to solve both issues with a [StreamTransformer](https://api.dart.dev/stable/2.9.1/dart-async/StreamTransformer-class.html).

Comment (knaeckeKami) [reply ferry/lib/src/client.dart:175]: Ah, I see. That's a good point.
However, I don't think this is possible with `await for`.

See the documentation:

> The final three functions are more special. They involve error handling which an await for loop can’t do—the first error reaching the loops will end the loop and its subscription on the stream. There is no recovering from that. You can use handleError() to remove errors from a stream before using it in an await for loop.
https://dart.dev/tutorials/language/streams#modify-stream-methods

and this dartpad:
https://dartpad.dartlang.org/f194fdda982f703da60d7d237f0c3d76

But in any case, the behaviour with .map() is wrong, it would emit an error when the original implementation would not. I think a StreamTranformer similar to the one in the linked dartpad would be the correct behaviour.

File: ferry/lib/src/client.dart [hunk 2]
```diff
@@ -172,14 +172,30 @@ class Client {
   Stream<QueryResponse<T>> _networkResponseStream<T>(
       QueryRequest<T> queryRequest) {
     try {
```
[the remark this answers is not in the document]
Comment (smkhalsa) [reply ferry/lib/src/client.dart:174]: Otherwise looks good. Thanks!

File: ferry/lib/src/client.dart [hunk 3]
```diff
@@ -118,19 +118,29 @@ class Client {
       case FetchPolicy.CacheAndNetwork:
         {
           final responseStreamFromNetwork =
-              _optimisticNetworkResponseStream(queryRequest).shareValue();
+              _optimisticNetworkResponseStream(queryRequest);
+
+          final StreamController<QueryResponse<T>> controller =
```
Comment (smkhalsa) [inline ferry/lib/src/client.dart:123]: I'm not sure why wrapping the stream in a new StreamController is necessary either.

Is it still necessary with the changes below using StreamController?

File: ferry/lib/src/client.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (knaeckeKami) [reply ferry/lib/src/client.dart:174]: The difference is that the link might throw a synchronous exception. The question is, do we want to convert this exception to a stream with an error event or if we should propagate this exception? I'm fine with both, if you think that throwing an exception is better, I'll get rid of the try/catch block.

File: ferry/lib/src/client.dart (hunk 3 above)
Comment (knaeckeKami) [reply ferry/lib/src/client.dart:123]: Yes, if I omit the wrapping, the test for propagating the cancel event to the link fails on the Fetchpolicy CacheAndNetwork (which is the default for Subscriptions, to that's kinda bad). 

However, I'm not sure why this is necessary. :/

File: ferry/lib/src/client.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (smkhalsa) [reply ferry/lib/src/client.dart:174]: It seems that this would only throw if there was an internal exception within the `Link.request` implementation. In that case, I think it'd be better to propagate the exception.

[the remark this answers is not in the document]
Comment (knaeckeKami) [reply ferry/lib/src/client.dart]: Ok, I removed the try/catch block.
I also needed to change a test to match the new behavior, and I added a new test.
These tests verify the following behavior:

 - if the link throws an exception, the Stream returned by the client emits an error event
 - if the link returns a Stream that emits an error event, the client wraps this error event into a QueryResponse

File: ferry/test/error_test.dart [hunk 4]
```diff
@@ -65,7 +64,69 @@ void main() {
...
+        options: ClientOptions(addTypename: false),
+      );
+
+      expect(client.responseStream(allPokemonReq),
+          emitsInOrder([isA<QueryResponse>(), isA<QueryResponse>()]));
+    });
+  });
 }
+
+abstract class Mockable {
```
Comment (smkhalsa) [inline ferry/test/error_test.dart:128]: Did you intend to leave the Mockable & MyMock classes in here?

**Review by smkhalsa — COMMENTED** [review]
I'd like to further investigate the FetchPolicy.CacheAndNetwork code at some point to better understand what's going on, but I think these changes are fine for now. There may be a way to refactor that doesn't require the use of `shareValue` at all. 

Thanks again for the PR!

File: ferry/test/error_test.dart (hunk 4 above)
Comment (knaeckeKami) [reply ferry/test/error_test.dart]: Ah, my bad. Of course not.

**Review by smkhalsa — APPROVED** [review]
LGTM, although it's still a draft PR so it can't yet be merged.
